#! /bin/bash -v
# This file runs a series of tests for ospfsfixer.

# First test
./ospfsfix

# Next test: checks if valid file
./ospfsfix not-a-file

# Next test: a completely valid image
./ospfsfix fsCONTROL.img

# Next test: NINODES is incorrect
./ospfsfix fsNINODES.img

# Next test: NBLOCKS is incorrect
./ospfsfix fsNBLOCKS.img

# Next test: MAGIC_NUMBER is incorrect
./ospfsfix fsMAGIC.img

# Next test: FIRSTINOB is shifted
./ospfsfix fsFIRSTINOB.img